# Generated by Django 6.1.1 on 2026-09-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='purpose',
            field=models.CharField(choices=[('register', 'تسجيل طالب'), ('password_reset', 'استعادة كلمة المرور'), ('contact', 'تحقق زائر')], max_length=20),
        ),
    ]
