# Generated by Django 6.1.1 on 2026-09-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_onetimecode_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_title_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='academic_title_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='public_profile',
            field=models.BooleanField(default=False),
        ),
    ]
