# Generated by Django 6.1.1 on 2026-09-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='grading_days_limit',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='planned_lectures_per_week',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='upload_min_percent',
            field=models.PositiveSmallIntegerField(default=75),
        ),
    ]
