# Generated by Django 6.1.1 on 2026-09-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_report_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_en',
            field=models.TextField(blank=True),
        ),
    ]
