# Generated by Django 6.1.1 on 2026-09-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_program_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='total_credit_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('total_credit_hours__isnull', True), models.Q(('total_credit_hours__gte', 1), ('total_credit_hours__lte', 300)), _connector='OR'), name='program_total_credit_hours_range'),
        ),
    ]
