# Generated by Django 6.1.1 on 2026-09-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_program_total_credit_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='annual_fee_sdg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='annual_fee_usd',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='careers_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='careers_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='outcomes_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='outcomes_en',
            field=models.TextField(blank=True),
        ),
    ]
