# Generated by Django 6.1.1 on 2026-09-27 21:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='imports/students/%Y/%m/')),
                ('status', models.CharField(choices=[('validated', 'جاهز للاعتماد'), ('has_errors', 'به أخطاء'), ('committed', 'معتمد'), ('rejected', 'مرفوض')], max_length=12)),
                ('summary', models.JSONField(default=dict)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('committed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField()),
                ('raw', models.JSONField(default=dict)),
                ('normalized', models.JSONField(default=dict)),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('skip', 'بلا تغيير'), ('error', 'خطأ')], max_length=10)),
                ('changes', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='students.studentimportbatch')),
            ],
            options={
                'ordering': ['row_no'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_no'), name='uniq_import_row')],
            },
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('university_number', models.CharField(max_length=30, unique=True)),
                ('full_name_ar', models.CharField(max_length=200)),
                ('full_name_en', models.CharField(blank=True, max_length=200)),
                ('level', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('active', 'منتظم'), ('suspended', 'موقوف'), ('graduated', 'متخرج'), ('withdrawn', 'منسحب')], default='active', max_length=12)),
                ('email', models.EmailField(blank=True, help_text='Official email from the college file.', max_length=254)),
                ('phone_e164', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=60)),
                ('national_id_hash', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('admitted_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academic.term')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='organization.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='organization.program')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['university_number'],
                'indexes': [models.Index(fields=['program', 'level', 'status'], name='students_st_program_e74939_idx'), models.Index(fields=['department', 'status'], name='students_st_departm_2566b5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 10)), name='student_level_range')],
            },
        ),
        migrations.CreateModel(
            name='UniversityNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('prefix', models.CharField(max_length=10)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.college')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('college', 'year', 'prefix'), name='uniq_university_number_sequence')],
            },
        ),
    ]
