# Generated by Django 6.1.1 on 2026-09-28 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0004_notifications'),
        ('organization', '0002_report_thresholds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('department', 'تقرير القسم'), ('teachers', 'أداء هيئة التدريس'), ('admissions', 'القبول والتسجيل'), ('affairs', 'شؤون الطلاب')], max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('data', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('digest', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.department')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academic.term')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
