# Generated by Django 6.1.1 on 2026-09-27 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('manual', 'يدوي'), ('system', 'تلقائي'), ('hr_notice', 'تنبيه موارد بشرية')], default='manual', max_length=10)),
                ('category', models.CharField(choices=[('course', 'المواد'), ('college', 'الكلية'), ('results', 'النتائج'), ('account', 'الحساب'), ('hr', 'الموارد البشرية')], max_length=10)),
                ('priority', models.CharField(choices=[('normal', 'عادي'), ('urgent', 'عاجل')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True, max_length=2000)),
                ('action_url', models.CharField(blank=True, max_length=300)),
                ('audience', models.JSONField(default=dict)),
                ('channels', models.JSONField(default=list)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('fanned_out_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(blank=True, help_text='Empty for system notifications.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(max_length=160)),
                ('body', models.TextField(max_length=4000)),
                ('requires_ack', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_notices', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notifications.notification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('inapp', 'داخل التطبيق'), ('push', 'Push'), ('email', 'بريد')], default='email', max_length=10)),
                ('to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'بانتظار الإرسال'), ('sent', 'أُرسل'), ('failed', 'فشل')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_try_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'next_try_at'], name='notificatio_status_7e1562_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('course', 'المواد'), ('college', 'الكلية'), ('results', 'النتائج'), ('account', 'الحساب'), ('hr', 'الموارد البشرية')], max_length=10)),
                ('inapp', models.BooleanField(default=True)),
                ('push', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
                'constraints': [models.UniqueConstraint(fields=('user', 'category'), name='uniq_preference')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notificatio_user_id_b9cd65_idx')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'user'), name='uniq_recipient')],
            },
        ),
    ]
