# Generated by Django 6.1.1 on 2026-09-28 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_notifications'),
        ('notifications', '0001_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrnotice',
            name='cc_department_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrnotice',
            name='evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hrnotice',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrnotice',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academic.term'),
        ),
        migrations.AddField(
            model_name='hrnotice',
            name='topic',
            field=models.CharField(choices=[('grading', 'تأخر التصحيح'), ('uploads', 'انتظام الرفع'), ('live', 'البث المباشر'), ('replies', 'الرد على الطلاب'), ('other', 'أخرى')], default='other', max_length=10),
        ),
    ]
