# Generated by Django 6.1.1 on 2026-09-27 23:52

import admissions.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0004_notifications'),
        ('contacts', '0002_visitorsession'),
        ('organization', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academic.academicyear')),
            ],
            options={
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference_no', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_e164', models.CharField(blank=True, max_length=20)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مُقدَّم'), ('under_review', 'قيد المراجعة'), ('missing_documents', 'مستندات ناقصة'), ('eligible', 'مؤهل'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('waitlisted', 'قائمة الانتظار'), ('registered', 'سُجّل طالبًا'), ('activated', 'فعّل حسابه'), ('withdrawn', 'منسحب'), ('expired', 'منتهٍ')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('assigned_registrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='contacts.contact')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='students.studentrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='admissions.application')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('doc_type', models.CharField(max_length=50)),
                ('file', models.FileField(max_length=255, upload_to=admissions.models._document_path)),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('mime', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'بانتظار المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application')),
            ],
            options={
                'ordering': ['application', 'doc_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('retired', 'متقاعد')], default='draft', max_length=10)),
                ('schema', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='form_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='admissions.applicationformtemplate'),
        ),
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('portal', 'صفحة المتابعة'), ('email', 'بريد'), ('internal', 'ملاحظة داخلية')], max_length=10)),
                ('body', models.TextField(max_length=4000)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='admissions.application')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='admissions.application')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Empty = the applicant or the system.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_open', models.BooleanField(default=True)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('requirements_ar', models.TextField(blank=True)),
                ('requirements_en', models.TextField(blank=True)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='admissions.admissioncycle')),
                ('form_template', models.ForeignKey(blank=True, help_text="Empty = the college's default published template.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='admissions.applicationformtemplate')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intakes', to='organization.program')),
            ],
            options={
                'ordering': ['cycle', 'program__name_ar'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admissions.programintake'),
        ),
        migrations.AddConstraint(
            model_name='admissioncycle',
            constraint=models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='cycle_window_order'),
        ),
        migrations.AddConstraint(
            model_name='applicationformtemplate',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uniq_template_version'),
        ),
        migrations.AddConstraint(
            model_name='programintake',
            constraint=models.UniqueConstraint(fields=('cycle', 'program'), name='uniq_intake_program'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['intake', 'status'], name='admissions__intake__601c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['contact'], name='admissions__contact_1e79b1_idx'),
        ),
    ]
