# Generated by Django 6.1.1 on 2026-09-30 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_date_published_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='figures',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founded_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='licence_ar',
            field=models.CharField(blank=True, help_text='e.g. the ministry licence and decision number.', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='licence_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='licence_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='office_hours_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='office_hours_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='share_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset'),
        ),
    ]
