# Generated by Django 6.1.1 on 2026-10-01 15:06

from django.db import migrations, models


def gallery_as_grid(apps, schema_editor):
    """The existing gallery page starts as a grid; other pages keep one image per row."""
    apps.get_model("content", "Page").objects.filter(slug="gallery").update(image_layout="grid")


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_site_trust_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_layout',
            field=models.CharField(choices=[('single', 'صورة في كل سطر'), ('grid', 'شبكة')], default='single', max_length=10),
        ),
        migrations.RunPython(gallery_as_grid, migrations.RunPython.noop),
    ]
