# Generated by Django 6.1.1 on 2026-09-27 22:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0003_ordering'),
        ('files', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(choices=[('theory', 'نظري'), ('lab', 'عملي')], default='theory', max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='academic.courseoffering')),
            ],
            options={
                'ordering': ['offering', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('homework', 'واجب'), ('project', 'مشروع'), ('report', 'تقرير'), ('lab', 'تجربة عملية')], default='homework', max_length=10)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField()),
                ('late_until', models.DateTimeField(blank=True, null=True)),
                ('late_policy', models.CharField(choices=[('none', 'لا يُقبل التأخير'), ('allow', 'يُقبل ويُعلَّم متأخرًا'), ('penalty', 'يُقبل بخصم')], default='none', max_length=10)),
                ('late_penalty_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('max_grade', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('submission_types', models.JSONField(default=list)),
                ('allowed_extensions', models.JSONField(blank=True, default=list)),
                ('max_file_size_mb', models.PositiveSmallIntegerField(default=20)),
                ('max_files', models.PositiveSmallIntegerField(default=3)),
                ('allow_resubmission', models.BooleanField(default=True)),
                ('grading_mode', models.CharField(choices=[('manual', 'يدوي'), ('rule', 'بقواعد')], default='manual', max_length=10)),
                ('rubric', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('closed', 'مغلق')], default='draft', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.courseoffering')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='learning.lecture')),
            ],
            options={
                'ordering': ['offering', 'due_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LectureResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('file', 'ملف'), ('video', 'فيديو'), ('link', 'رابط'), ('recording', 'تسجيل')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.storedfile')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='learning.lecture')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.videoasset')),
            ],
            options={
                'ordering': ['lecture', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_submitted_at', models.DateTimeField()),
                ('is_late', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='learning.assignment')),
                ('student_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='students.studentrecord')),
            ],
            options={
                'ordering': ['assignment', 'student_record__university_number'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('feedback', models.TextField(blank=True)),
                ('rubric_scores', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('manual', 'يدوي'), ('rule', 'بقواعد'), ('ai_suggested', 'مقترح ذكي')], max_length=15)),
                ('status', models.CharField(choices=[('suggested', 'مقترح'), ('approved', 'معتمد')], max_length=10)),
                ('graded_at', models.DateTimeField(null=True)),
                ('graded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='learning.submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveSmallIntegerField()),
                ('content', models.TextField(blank=True)),
                ('files', models.JSONField(default=list)),
                ('links', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField()),
                ('is_late', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='learning.submission')),
            ],
            options={
                'ordering': ['submission', 'version_no'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='current_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='learning.submissionversion'),
        ),
        migrations.CreateModel(
            name='AssignmentLinkField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('url_pattern', models.CharField(blank=True, help_text='Optional regex.', max_length=200)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_fields', to='learning.assignment')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'label'), name='uniq_link_field_label')],
            },
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['offering', 'is_published'], name='learning_le_offerin_b4f0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['offering', 'status'], name='learning_as_offerin_21604a_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('late_until__isnull', True), ('late_until__gte', models.F('due_at')), _connector='OR'), name='assignment_late_after_due'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('late_penalty_percent__lte', 100)), name='assignment_penalty_range'),
        ),
        migrations.AddConstraint(
            model_name='lectureresource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('file__isnull', False), ('url', ''), ('video__isnull', True)), models.Q(('file__isnull', True), ('url', ''), ('video__isnull', False)), models.Q(('file__isnull', True), ('video__isnull', True), models.Q(('url', ''), _negated=True)), _connector='OR'), name='resource_single_target'),
        ),
        migrations.AddConstraint(
            model_name='submissiongrade',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='grade_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='submissionversion',
            constraint=models.UniqueConstraint(fields=('submission', 'version_no'), name='uniq_submission_version'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student_record'), name='uniq_submission_per_student'),
        ),
    ]
