# Generated by Django 6.1.1 on 2026-09-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
