# Generated by Django 6.1.1 on 2026-10-01 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_notifications'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('times', models.PositiveIntegerField(default=1)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='learning.lecture')),
                ('student_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.studentrecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lecture', 'student_record'), name='uniq_lecture_view')],
            },
        ),
    ]
