# Generated by Django 6.1.1 on 2026-09-27 23:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0004_notifications'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('grace_seconds', models.PositiveSmallIntegerField(default=30)),
                ('pass_marks', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('max_attempts', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('allow_backtrack', models.BooleanField(default=True)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_choices', models.BooleanField(default=False)),
                ('result_visibility', models.CharField(choices=[('immediate', 'فور الإرسال'), ('after_close', 'بعد الإغلاق'), ('manual', 'يدويًا')], default='immediate', max_length=12)),
                ('show_answers', models.BooleanField(default=False, help_text='Let students review correct answers and explanations.')),
                ('results_released', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('closed', 'مغلق'), ('archived', 'مؤرشف')], default='draft', max_length=10)),
                ('reminder_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic.courseoffering')),
            ],
            options={
                'ordering': ['-opens_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField()),
                ('deadline_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'جارية'), ('submitted', 'أُرسلت'), ('auto_submitted', 'أُرسلت تلقائيًا'), ('invalidated', 'أُلغيت')], default='in_progress', max_length=16)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('question_order', models.JSONField(default=list)),
                ('choice_orders', models.JSONField(default=dict)),
                ('client_meta', models.JSONField(blank=True, default=dict)),
                ('last_saved_at', models.DateTimeField(blank=True, null=True)),
                ('invalidation_reason', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('student_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_attempts', to='students.studentrecord')),
            ],
            options={
                'ordering': ['exam', 'student_record__university_number', 'attempt_no'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(choices=[('single', 'اختيار واحد'), ('multiple', 'اختيارات متعددة'), ('true_false', 'صح / خطأ'), ('fill_blank', 'إكمال فراغ'), ('short_answer', 'إجابة قصيرة'), ('essay', 'مقالي')], max_length=14)),
                ('text', models.TextField()),
                ('marks', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('explanation', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_required', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'ordering': ['exam', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.question')),
            ],
            options={
                'ordering': ['question', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, null=True)),
                ('saved_at', models.DateTimeField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('needs_manual', models.BooleanField(default=False)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examattempt')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.question')),
            ],
            options={
                'ordering': ['attempt', 'question__order'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['offering', 'status'], name='exams_exam_offerin_646b34_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status', 'closes_at'], name='exams_exam_status_53b851_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='exam_window_order'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status', 'deadline_at'], name='exams_exama_status_d73dd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('exam', 'student_record', 'attempt_no'), name='uniq_attempt_no'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('exam', 'student_record'), name='one_attempt_in_progress'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_answer_per_question'),
        ),
    ]
