# Generated by Django 6.1.1 on 2026-09-27 23:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0004_notifications'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scope', models.CharField(choices=[('offering', 'مادة'), ('cohort', 'دفعة (برنامج ومستوى)')], max_length=10)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('zoom', 'Zoom'), ('other', 'أخرى')], max_length=10)),
                ('join_url_encrypted', models.TextField(help_text='Encrypted at rest (core.crypto).')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('cancelled', 'ملغاة')], default='scheduled', max_length=10)),
                ('recording_url', models.URLField(blank=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='academic.courseoffering')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.program')),
            ],
            options={
                'ordering': ['starts_at', 'id'],
                'indexes': [models.Index(fields=['starts_at', 'status'], name='live_livese_starts__b69890_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('level__isnull', True), ('offering__isnull', False), ('program__isnull', True), ('scope', 'offering')), models.Q(('level__isnull', False), ('offering__isnull', True), ('program__isnull', False), ('scope', 'cohort')), _connector='OR'), name='live_session_single_scope'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='live_session_time_order')],
            },
        ),
    ]
