# Generated by Django 6.1.1 on 2026-09-27 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0004_notifications'),
        ('files', '0002_alter_storedfile_offering_alter_storedfile_purpose'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('academic', 'أكاديمية'), ('exams', 'الامتحانات'), ('conduct', 'السلوك'), ('general', 'عامة')], default='general', max_length=10)),
                ('version', models.CharField(default='1', max_length=20)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('requires_acknowledgement', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشورة'), ('superseded', 'مستبدلة')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.storedfile')),
                ('replaces', models.ForeignKey(blank=True, help_text='The version this one supersedes when published.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='student_affairs.regulation')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('academic', 'حالة أكاديمية'), ('exam_misconduct', 'غش امتحان'), ('conduct', 'مخالفة سلوكية'), ('welfare', 'حالة اجتماعية/صحية')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('decision', models.TextField(blank=True)),
                ('sanction', models.CharField(blank=True, max_length=200)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('decided', 'صدر قرار'), ('closed', 'مغلقة')], default='open', max_length=8)),
                ('published_to_student', models.BooleanField(default=False)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='students.studentrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MisconductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('evidence', models.TextField()),
                ('status', models.CharField(choices=[('new', 'جديد'), ('converted', 'حُوّل إلى حالة'), ('dismissed', 'رُفض')], default='new', max_length=10)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='misconduct_reports', to='academic.courseoffering')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='misconduct_reports', to='students.studentrecord')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='student_affairs.studentcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentCaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opened', 'فُتحت'), ('note', 'ملاحظة'), ('decided', 'قرار'), ('published', 'نُشرت للطالب'), ('closed', 'أُغلقت'), ('reopened', 'أُعيد فتحها')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='student_affairs.studentcase')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegulationAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='student_affairs.regulation')),
                ('student_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='students.studentrecord')),
            ],
            options={
                'ordering': ['-at'],
                'constraints': [models.UniqueConstraint(fields=('regulation', 'student_record'), name='uniq_acknowledgement')],
            },
        ),
        migrations.AddIndex(
            model_name='studentcase',
            index=models.Index(fields=['student_record', 'status'], name='student_aff_student_c13ef4_idx'),
        ),
    ]
