# Generated by Django 6.1.1 on 2026-09-27 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('student_affairs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='misconductreport',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misconduct_reports', to='exams.examattempt'),
        ),
    ]
