# Generated by Django 6.1.1 on 2026-09-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_affairs', '0002_misconductreport_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
