# Generated by Django 6.1.1 on 2026-09-27 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference_no', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('admission', 'القبول'), ('programs', 'البرامج'), ('registration', 'التسجيل'), ('fees', 'الرسوم'), ('study', 'الدراسة'), ('technical', 'مشكلة تقنية'), ('general', 'عام')], max_length=14)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=4000)),
                ('status', models.CharField(choices=[('new', 'جديد'), ('in_progress', 'قيد المعالجة'), ('waiting_for_user', 'بانتظار الزائر'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], default='new', max_length=18)),
                ('source', models.CharField(choices=[('web', 'الموقع'), ('whatsapp', 'WhatsApp'), ('phone', 'هاتف'), ('email', 'بريد')], default='web', max_length=10)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='contacts.contact')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('portal', 'الموقع'), ('email', 'بريد'), ('whatsapp_note', 'WhatsApp'), ('internal', 'ملاحظة داخلية')], max_length=14)),
                ('body', models.TextField(max_length=4000)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, help_text='Empty = the visitor.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inquiries.inquiry')),
            ],
            options={
                'ordering': ['sent_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InquiryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=18)),
                ('to_status', models.CharField(max_length=18)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inquiries.inquiry')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['status', 'type'], name='inquiries_i_status_b89e47_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['department', 'status'], name='inquiries_i_departm_38babb_idx'),
        ),
    ]
