# Generated by Django 6.1.1 on 2026-09-27 22:20

import django.db.models.deletion
import files.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0003_ordering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('local', 'محلي'), ('bunny', 'Bunny Stream')], max_length=10)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('file', models.FileField(blank=True, max_length=255, upload_to='videos/%Y/%m/')),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'قيد الرفع'), ('processing', 'قيد المعالجة'), ('ready', 'جاهز'), ('failed', 'فشل')], default='uploading', max_length=12)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='academic.courseoffering')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('lecture', 'مورد محاضرة'), ('submission', 'تسليم واجب')], max_length=20)),
                ('file', models.FileField(max_length=255, upload_to=files.models._upload_to)),
                ('name', models.CharField(help_text='Original name, shown on download.', max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('mime', models.CharField(max_length=100)),
                ('sha256', models.CharField(max_length=64)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='academic.courseoffering')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purpose', 'offering'], name='files_store_purpose_ff238b_idx')],
            },
        ),
    ]
