# Generated by Django 6.1.1 on 2026-09-27 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_notifications'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='offering',
            field=models.ForeignKey(blank=True, help_text='Course files only; regulations and case attachments have none.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='academic.courseoffering'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='purpose',
            field=models.CharField(choices=[('lecture', 'مورد محاضرة'), ('submission', 'تسليم واجب'), ('regulation', 'لائحة'), ('case', 'مرفق حالة طالب')], max_length=20),
        ),
    ]
