# Generated by Django 6.1.1 on 2026-09-27 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(max_length=64)),
                ('target_repr', models.CharField(max_length=255)),
                ('old', models.JSONField(blank=True, null=True)),
                ('new', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.department')),
            ],
            options={
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx'), models.Index(fields=['actor', 'at'], name='audit_audit_actor_i_3f9ba5_idx'), models.Index(fields=['department', 'at'], name='audit_audit_departm_66e78d_idx')],
            },
        ),
    ]
