# Generated by Django 6.1.1 on 2026-09-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentmembership',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='offeringinstructor',
            options={'ordering': ['id']},
        ),
    ]
