# Generated by Django 6.1.1 on 2026-09-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='ta_can_notify',
            field=models.BooleanField(default=False, help_text="TAs may send notifications to this course's students."),
        ),
    ]
